### ISSUE TITLE
daemon bug with connect

### ISSUE THREAD

**Issue by FlorentinLedy** [SchokkerIT/GameDash#28]
**Describe the bug**
After the creation of a node and his installation, the link between deamon and website don't work.

**To Reproduce**
1. Create node
2. Make installation of the node

**Expected behavior**
the link between deamon and website don't work

**Screenshots**
http://prnt.sc/tm4xfv
https://prnt.sc/tm4xpz
https://prnt.sc/tm4y2d

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 84.0.4147.89 (64 bits)

**Additional context**
[ERROR] [2020-07-21 21:12:53,530] [main] (Application.java:105) - com.gamedash.daemon.common.license.domain.LicenseDomainNotFoundException: License domain api.panel.flyserv.net could not be found
	at com.gamedash.daemon.license.License.validate(License.java:15)
	at com.gamedash.daemon.Init.initLicense(Init.java:245)
	at com.gamedash.daemon.Init.initServices(Init.java:197)
	at com.gamedash.daemon.Application.run(Application.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.gamedash.daemon.wrapper.version.application.ApplicationLoader.start(ApplicationLoader.java:57)
	at com.gamedash.daemon.wrapper.Application.run(Application.java:40)
	at com.gamedash.daemon.wrapper.Main.main(Main.java:23)

**Comment by kainick** [comment]
Domain is not authorized, you need to use the api domain you gave to Jesse when you received your access key.

**Comment by FlorentinLedy** [comment]
indeed thank you
